---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role create_pkg
#
# Overview:
# Creates packages from edX single server installation
#
#

- name: Install apt package dependencies
  apt: pkg={{ item }}
  with_items: create_pkg_debian_pkgs

- name: Install fpm
  shell: >
    gem install fpm
    creates=/usr/local/bin/fpm

- name: Create fpm templates
  template: >
    src={{ item }}.j2
    dest=/var/tmp/{{ item }}
  with_items:
    - fpm-base.sh
    - fpm-xqueue.sh
    - fpm-edxapp.sh
